=== Configuration du plugin

Le plugin ne comporte pas de configuration générale.

Le plugin utilise un service en python qui permet d'utiliser :

  - les capteurs Zigbee Xiaomi reliés à une gateway Wifi Aqara Lumi (création des équipements automatique)

  - les ampoules/lampes Yeelight Wifi (le plugin dispose d'un bouton de scan qui créer automatiquement les ampoules découvertes)

  - différents périphériques Xiaomi qui fonctionnnent en Wifi

=== Création des équipements

Les équipements Aqara et Yeelight sont créés automatiquement

Pour les capteurs Aqara, c'est à leur remontée d'information, donc la fréquence varie en fonction du modèle et ses caractéristiques.

Pour les interrupteurs et boutons Aqara, il peut être nécessaire de les activer pour avoir la création des commandes (un clic par exemple)

Pour les Yeelight, elles sont reconnues par le plugin quand elles s'annoncent, elles font une annonce par heure et quand elles sont branchées/allumées. Un bouton de scan est également disponible

==== Création des équipements Wifi

Pour les équipements Wifi supplémentaires, il faut faire un ajout manuel.

Il faut renseigner pour tous les équipements supportés : adresse IP et sélectionner le type dans le ménu déroulant.

Il vous faut également le token. Pour obtenir le token, il suffit de cliquer sur le bouton bleu "Récupérer les infos", dans le cas où le token récupéré est une suite de 0 seulement ou de f seulement, il faut alors le récupérer manuellement avec la procédure ci-dessous

===== Récupérer le token d'un équipement manuellement

Pour le robot entre autre, il est nécessaire de récupérer le token manuellement avant son intégration dans Mi Home.

Pour cela, on doit d'abord le reseter (appuyer sur le bouton reset à proximité des boutons on/home) afin qu'il initialise son point d'accès Wifi

Avec un PC on se connecte à ce réseau Wifi (il contient robo, facile à trouver et n'a pas de mot de passe)

De là, il y a un petit utilitaire à lancer qui va vous permettre de récupérer le token, voilà vous l'avez

Là vous pouvez l'intégrer dans Mi Home pour configurer votre Wifi et l'ajouter dans le plugin avec son IP et le token

Attention, tout reset le Robot change de token et donc il faut refaire la procédure pour récupérer le token

La même procédure s'applique pour tout équipement qui ne fournirait pas son token automatiquement (Rice Cooker, Robot par exemple)

=== Configuration de la gateway Aqara

Une présentation complète de la gamme est disponible ici : https://lunarok-domotique.com/plugins-jeedom/xiaomi-home-jeedom/aqara-lumi-xiaomi-smart-home-security/[Article de présentation]

Il est par contre nécessaire de paramétrer la gateway pour activer l'API locale

Pour cela, il faut ajouter la Gateway dans l'application Mi Home et être en China Mainland et Chinese (oui du coup des écrans peuvent contenir beaucoup de caractères illisibles à moins de maitriser le mandarin)

Ensuite cliquer dessus pour la sélectionner, là cliquer sur les "..." et enfin "about"

Là vous avez un numéro de version, cliquez dessus de facon répéter jusqu'à un message (oui en chinois ca aide pas :)) et 2 nouvelles options apparaissent

Choisissez la première option (nouvellement apparue) et activer le bouton switch pour qu'il passe en vert, voilà le mode local est actif et votre gateway est accessible du réseau

Information importante : pour pouvoir envoyer des commandes (prise) vers la gateway, vous devez renseigner son mot de passe sur la page équipement. Ce mot de passe est visible sur la page où l'on active le mode développeur

==== Commandes des équipements compatibles

Les équipements actuellement compatibles fournissent les informations :

  - Gateway : anneau RGB (avec couleur et intensité, pour éteindre il faut absolument mettre l'intensité à 0), capteur de luminosité, jouer les sons enregistrés (0 à 8, 10 à 13, 20+ correspondent aux sons par défaut dans Mihome, 10000 pour éteindre, 10001 et plus pour les sons personnalisés) https://lunarok-domotique.com/2017/03/mi-smart-gateway-domotique-jeedom/[Présentation]

  - Détecteur de mouvement : commande statut de type binaire activée sur mouvement

  - Détecteur d'ouverture : commande statut de type binaire activée sur ouverture

  - Capteur température/humidité : commande température, commande humidité

  - Bouton Switch : commande statut avec pour valeurs click, double_click, long_click_press, long_click_release

  - Prise : commande statut binaire avec on et off, état d'utilisation et consommation

  - Interrupteur mural : commande statut pour chaque interrupteur (click, double_click) et si double une commande qui donne l'appui simultané

  - Interrupteur encastré : commande statut binaire avec on et off pour chaque interrupteur

  - Cube : commande statut avec pour valeur move, tap_twice, shake_air, alert, flip90, flip180, free_fall et une commande rotate avec la valeur en degré du mouvement https://lunarok-domotique.com/2017/03/aqara-xiaomi-magic-controller-utilisation-dans-jeedom/[Présentation]

Remontée des piles : l'API fournie désormais aussi l'état des piles des équipements. Ce qui est retourné c'est le voltage de la pile, avec une fiche technique de l'API indiquant qu'elle sera au max de 3.2V et logiquement à 2.8V la pile n'est plus utilisable. Dans les faits, ce sont des piles 3V, voici donc les informations fournies dans Jeedom :

  * Voltage (en commande non visible sur le dash par défaut)

  * Batterie (en statut standard, mais aussi en commande non visible) : sa valeur est considérée à 100% si supérieure ou égale à 3V, puis décroit à 0% pour 2.8V

  * Le type de pile est indiqué pour chaque équipement sur le récapitulatif


=== Configuration des lampes Yeelight

Une présentation complète de la gamme est disponible ici : https://lunarok-domotique.com/plugins-jeedom/xiaomi-home-jeedom/yeelight-xiaomi-wifi-lamp/[Article de présentation]

Dans l'application Yeelight vous devez activer l'option développeur également

C'est un switch a activé dans les options de chaque ampoule/bandeau

==== Commandes des équipements compatibles

Les lampes compatibles proposent les commandes suivantes par défaut : on / off / toggle / luminosité / enchainement

Certaines lampes ajoutent des commandes :

  - Yeelight Blanc et Desklamp : pas d'autres commandes

  - Yeelight RGB et bandeau LED : couleur RGB, couleur de blanc, mode jour, mode nuit, couleurs HSV

  - Yeelight Ceiling : couleur blanc, mode jour, mode nuit

===== Commande enchainement des Yeelight

Pour les Yeelight, une commande spéciale est créée qui a vocation à être utilisée en scénario seulement car on doit envoyer un contenu précis à la commande.

C'est une commande message qui doit avoir par exemple :

3 recover rgb,255,0,0,500,100-wait,400-rgb,255,255,0,500,100

- 3 : c'est un chiffre représentant le nombre de fois que la suite d'effets doit être appliquée avant de s'arrêter (0 veut dire illimité)

- recover : une des 3 options possible (recover = retour à l'état avant effet, off = s'eteint ensuite, stay = reste au statut de fin de boucle)

- le troisième élément est la suite des états avec leur transition, il y en a 4 possible (attention à bien ne pas mettre d'espaces)

  - hsv : pramètres (hue,saturation,duration=300,brightness=100)

  - rgb : pramètres (red,green,blue,duration=300,brightness=100)

  - temp : pramètres (degrees,duration=300,brightness=100)

  - wait(duration=300)

Il faut bien entrer l'enchainement avec des - entre chaque effet. Et pour un enchainement il doit y avoir son nom et tous les paramètres séparés par des virgules

=== Configuration des équipements Wifi

Cette section traite des équipements Wifi additionnels, pas Yeelight ni la gateway Aqara

  - Xiaomi Mi Robot Vacuum : statut, batterie, aspiration (force + slider, attention au delà de 77 vous dépasser le mode turbo), résumé, statut d'erreurs, démarrer, arrêter, pause, retour socle, "ou es-tu ?"

  - Xiaomi Smart Mi Air Purifier : statut, qualité d'air, humidité, température, filtre, vitesse, buzzer (on/off), led (action dessus aussi), démarrer/arrêter (avec les différents modes disponibles)

  - Xiaomi Smart Ultrasonic Humidifier : statut, mode, humidité, humidité cible (+slider de set), température, buzzer (statut + activation), led (statut + activation), démarrer/arrêter (avec les différents modes disponibles)

  - Xiaomi Smart Air Quality Monitor PM2.5 Detector : qualité d'air, batterie, rafraichir

  - Xiaomi Mi Electric Rice Cooker :

  - Xiaomi Philips Eyecare Smart Lamp : statut, on/off, luminosité (+slider), eyecare (statut, scenes + différents modes disponibles)
